-- Run in Supabase SQL editor. Projects + tasks.project_id.
CREATE TABLE IF NOT EXISTS projects (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE tasks ADD COLUMN IF NOT EXISTS project_id bigint REFERENCES projects (id);

-- Backfill: one default project for existing tasks without project_id
INSERT INTO projects (name)
SELECT 'Default project'
WHERE NOT EXISTS (SELECT 1 FROM projects);

UPDATE tasks
SET project_id = (SELECT id FROM projects ORDER BY id LIMIT 1)
WHERE project_id IS NULL;

ALTER TABLE tasks ALTER COLUMN project_id SET NOT NULL;
